### ISSUE TITLE
Integrate with FeedMe

### ISSUE THREAD

**Issue by nilsnh** [codemonauts/craft-readonly-field#2]
Hi and thanks for creating this plugin. 😃 I would like to use this plugin for a read-only id field imported via FeedMe. But I was not able to import to the field when configuring the FeedMe feed. To fix this it seems possible to [register this field with FeedMe](https://docs.craftcms.com/feed-me/v4/developers/field-types.html#the-registerfeedmefields-event).

**Comment by nilsnh** [comment]
Btw, I might have time to create a pull request for this.

**Comment by kringkaste** [comment]
Hey @nilsnh, I add support for the Feed Me Plugin in the latest release. Would be nice, if you could test it as well.
