### ISSUE TITLE
Feature Request: Sortable

### ISSUE THREAD

**Issue by mrnebbi** [codemonauts/craft-readonly-field#3]
This field is fantastic for what we need, but is there a way to make it sortable?

When applied to user accounts, the field is displayed as a column in the Users view, but can't be used to sort.

**Comment by fleaz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [readonly-field: Sortable](https://trello.com/c/JnS91t6T/21-readonly-field-sortable)

**Comment by kringkaste** [comment]
FYI: With release 2.0 the field is now sortable.
