### ISSUE TITLE
Can't install if FeedMe isn't installed

### ISSUE THREAD

**Issue by daltonrooney** [codemonauts/craft-readonly-field#5]
I get an error on installation: 

`Class 'craft\feedme\services\Fields' not found`

Looks like a problem[ here](https://github.com/codemonauts/craft-readonly-field/blob/c8d71a57ad484a98c18f6e53e74bd2a5f48ea55c/src/Readonly.php#L11)

**Comment by kringkaste** [comment]
Hi, I tried to install the plugin on a fresh Craft CMS installation and I could not reproduce your error. Could you provide more informations? Did you get a stack trace?  Craft and php version? How do you try to install the plugin (CLI or GUI)?

The `use ...` only tells the compiler where to find a class. It does not try to import or do anything.

Are you sure you hadn't installed the feed-me plugin before at some point and hadn't disabled it before deleting it?

**Comment by daltonrooney** [comment]
> Are you sure you hadn't installed the feed-me 
> plugin before at some point and hadn't disabled 
> it before deleting it?

That is certainly possible. I’ll assume it’s a mistake on my end and will close the issue for now. Thanks for looking into it!
