### ISSUE TITLE
Error when installing plugin on PHP 8.1

### ISSUE THREAD

**Issue by codename-niels** [codemonauts/craft-readonly-field#6]
### Description

While installing the plugin the following error is thrown. I'm guessing this is an error that is thrown when using PHP version 8.1. "readonly" is a reserved name. Check [this article](https://php.watch/versions/8.1/readonly)

<details>
  <summary>syntax error, unexpected token \"readonly\", expecting identifier</summary>
<pre>
ParseError: syntax error, unexpected token "readonly", expecting identifier in /var/www/vendor/codemonauts/craft-readonly-field/src/Readonly.php:14
Stack trace:
#0 /var/www/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /var/www/vendor/craftcms/cms/src/services/Plugins.php(914): is_subclass_of()
#3 /var/www/vendor/craftcms/cms/src/services/Plugins.php(229): craft\services\Plugins->createPlugin()
#4 /var/www/vendor/craftcms/cms/src/base/ApplicationTrait.php(1487): craft\services\Plugins->loadPlugins()
#5 /var/www/vendor/craftcms/cms/src/web/Application.php(93): craft\web\Application->_postInit()
#6 /var/www/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#7 /var/www/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct()
#8 [internal function]: yii\base\Application->__construct()
#9 /var/www/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs()
#10 /var/www/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#11 /var/www/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#12 /var/www/vendor/craftcms/cms/src/Craft.php(66): yii\BaseYii::createObject()
#13 /var/www/vendor/craftcms/cms/bootstrap/bootstrap.php(242): Craft::createObject()
#14 /var/www/vendor/craftcms/cms/bootstrap/web.php(51): require('...')
#15 /var/www/public/index.php(20): require('...')
#16 {main}

</pre>
</details>

### Steps to reproduce

1. Setup a Craft project on a PHP 8.1 apache server
2. Install the plugin

### Additional info

- Craft version: 3.7
- PHP version: 8.1
- Database driver & version: MySQL

**Comment by kringkaste** [comment]
Hey! Thank for this hint. We just released version 2.0.0. This release is for Craft 4.0 and fixes this too.

**Comment by Karl456** [comment]
It would be great if this change was also implemented to work with Craft 3.7. Not everyone is ready to upgrade to 4 yet and this release forces you to upgrade Craft to version 4.

**Comment by kringkaste** [comment]
Hey @Karl456 , ok, we will also release a version for 3.x.

**Comment by Karl456** [comment]
Thank you @kringkaste, is there an ETA on this?

**Comment by kringkaste** [comment]
I think I will make it today...

**Comment by Karl456** [comment]
@kringkaste is there an ETA on this please?

**Comment by kringkaste** [comment]
@Karl456 I just release 1.0.2 with php 8.1 support.
